### ISSUE TITLE
:mag: Evaluation projet

### ISSUE THREAD

**Issue by adriens** [adriens/dev-to-slideshow#8]
# :dart: Objectif

En lisant le README, dérouler les étapes qui permettent de faire tourner la solution local.

**Comment by adriens** [comment]
Sur une machine vierge, je lance ceci : 


```shell
gh repo clone adriens/dev-to-slideshow
cd dev-to-slideshow
npm run dev
```

... ce qui m'amène à l'erreur suivante : 

![image](https://github.com/adriens/dev-to-slideshow/assets/5235127/d4a556fa-d6b1-45eb-9bc4-d29897bb35b9)

@flavienlbrt2003 : quels sont les prérequis à installer et les lignes de commandes à passer pour y arriver :grey_question:

**Comment by flavienlbrt2003** [comment]
Il semble qu'il manquait la commande "npm install". J'ai réctifié

**Comment by adriens** [comment]
Je teste...

**Comment by adriens** [comment]
Avec le script ci-dessous : 

```shell
gh repo clone adriens/dev-to-slideshow
cd dev-to-slideshow
npm install
npm run dev
```

j'ai ceci : 

<pre><span style="background-color:#2E3436"><font color="#D3D7CF">pm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">EBADENGINE</font>   current: { node: &apos;v12.22.9&apos;, npm: &apos;8.5.1&apos; }
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">EBADENGINE</font> }
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#C4A000"><font color="#2E3436">WARN</font></span> <font color="#75507B">deprecated</font> sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

added 714 packages, and audited 715 packages in 13s

81 packages are looking for funding
  run `npm fund` for details

found <font color="#8AE234"><b>0</b></font> vulnerabilities
<font color="#5FD700">❯</font> npm run dev

&gt; slideshowproject@0.0.0 dev
&gt; vite

file:///home/adriens/Github/dev-to-slideshow/node_modules/vite/bin/vite.js:7
    await import(&apos;source-map-support&apos;).then((r) =&gt; r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
<font color="#555753">    at Loader.moduleStrategy (internal/m</font></pre>

**Comment by flavienlbrt2003** [comment]
Il me semble que vous n'avez pas la bonne version de Node.js. Vous pouvez télécharger la dernière version sur https://nodejs.org/en/download. J'ai modifier le README.md.

**Comment by adriens** [comment]
> Il me semble que vous n'avez pas la bonne version de Node.js. Vous pouvez télécharger la dernière version sur https://nodejs.org/en/download. J'ai modifier le README.md.

SVP, rajouter cela à la doc des prérequis (documenter la commande de check,...) et la commande à passer au README.
Je déroulerai ensuite la suite de test

**Comment by flavienlbrt2003** [comment]
J'ai ajouté au README une partie prérequis pour tester l'application. Cela vous convient ?

**Comment by adriens** [comment]
je check

**Comment by adriens** [comment]
- Donner la version minimale à partir de laquelle ça marche
- La commande pour ugrader si on atteint pas le prérequis (commande système ou npm.... on ne redirige pas vers un site de download)

![image](https://github.com/adriens/dev-to-slideshow/assets/5235127/10a9fbd2-6edb-4452-806e-4e756cc44a95)

**Comment by adriens** [comment]
Fournir une video commentée qui montre la solution qui fonctionne avec le contenu dynamique mis à disposition par les APIs de DEV.to tel que décrit

![image](https://github.com/adriens/dev-to-slideshow/assets/5235127/80b12654-3c03-4e7f-aef0-efaa3f74b2ad)

**Comment by flavienlbrt2003** [comment]
C'est bon, le README à été modifié comme demandé.

**Comment by flavienlbrt2003** [comment]
Bonjour, il me faudrait la grille d'évaluation remplie s'il vous plaît, j'ai une date limite pour le rendre qui est déjà dépassé. Merci d'avance.

**Comment by adriens** [comment]
> Bonjour, il me faudrait la grille d'évaluation remplie s'il vous plaît, j'ai une date limite pour le rendre qui est déjà dépassé. Merci d'avance.

https://github.com/adriens/dev-to-slideshow/issues/1#issuecomment-1586479631
